name: Blog de Iván Basurto Delgado
url: 
description: Perfil Profesional de Iván Basurto Delgado, e información de Introducción a la Ingeniería de Software

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
